### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by F-alling** [Asu-chan/RiivolutionIsoBuilder#8]
error

```
Warning: This riivolution patch only applied to the game that has the TitleID RMCE.
Yours uses the TitleID RMC and therefore cannot be patched.
If you really know what you're doing and want to ignore this, try to run this tool again with the "--ignore-warnings" option.

C:\Users\Falling\Downloads\RiivolutionIsoBuilder>RiivolutionIsoBuilder.exe "C:\Users\Falling\Desktop\MarioKartWiiRMCE01.iso" "C:\Users\Falling\Downloads\InsaneKartWii120\riivolution\Insane_Kart_Wii_USA.xml" "C:\Users\Falling\Desktop\Insanewii.iso" --ignore-warnings
Asu's Riivolution ISO Builder - v1.0.0 - Build Date: 29/08/2022 21:25:58

Ignore Warnings: true
Parsing XML file...
Done parsing XML file, took 0.007s
TitleID found: RMCE01
Game name found: MarioKartWii

Warning: This riivolution patch only applied to the game that has the TitleID RMCE.
Yours uses the TitleID RMC and therefore cannot be patched.
No custom Title ID were specified, therefore your mod will use the same save slot as the game you're modding, which could cause issues with some mods!
Extracting ISO...
      0 [main] wit 17580 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com

wit: Wiimms ISO Tool v2.22c r4523 cygwin - Dirk Clemens - 2013-06-29

1 object scanned, 1 supported file found ...
1 object scanned, 1 supported file found.
!! wit: ERROR #14 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1932
!!      Partition 0 [DATA]: End of data (0x1156c0000) behind end of file (0xffff8000):
!!      /cygdrive/c/Users/Falling/Desktop/MarioKartWiiRMCE01.iso
!! wit: ERROR #14 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1921
!!      Partition 2 [CHANNEL]: Offset of TICKET (0x1156c0000) behind end of file (0xffff8000):
!!      /cygdrive/c/Users/Falling/Desktop/MarioKartWiiRMCE01.iso
wit: EXTRACT 1/1 ISO:/cygdrive/c/Users/Falling/Desktop/MarioKartWiiRMCE01.iso -> /cygdrive/c/Users/Falling/Downloads/RiivolutionIsoBuilder/Insane_Kart_Wii_USA-eVEo6b/
 - will extract 0 files of 0 partitions, 0 MiB total
        0 MiB copied in 0:00, 48.6 MiB/sec
ISO Extracted.
-Section: "Insane Kart Wii"
  Option: "Game Mode"
   Choices available:
    0. None
    1. Default!
    2. Item Rain!
    3. Random Items!
    4. High CC!
    5. Insane CC!
    6. Bumper Karts!
    7. Blueshell Madness!
    8. Mushroom Dash!
```
    9. Countdown!
    10. Infinite Acceleration!
    11. TTs Online!
    12. Crazy Items!
    13. Unfair Items!
    14. Vanilla Mode!
Please enter the number of the choice you want to use: 1
  Option: "My Stuff"
   Choices available:
    0. None
    1. My Stuff 1
    2. My Stuff 2
    3. My Stuff 3
    4. My Stuff 4
    5. My Stuff 5
    6. All
Please enter the number of the choice you want to use: 0
  Option: "Save to SD"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Enable Theme"
   Choices available:
    0. None
    1. Mario Kart 8
    2. Super Mario Kart
    3. MKDD
    4. Super Mario Odyssey
    5. MKW (Dolphin only)
    6. MK8 (Dolphin only)
    7. SMK (Dolphin only)
    8. MKDD (Dolphin only)
    9. SMO (Dolphin only)
Please enter the number of the choice you want to use: 0
  Option: "Enable Custom Font"
   Choices available:
    0. None
    1. Mario Kart 8
    2. Chikaraduyoku
    3. Comicreggae
    4. Splatoon 2
Please enter the number of the choice you want to use: 0
  Option: "No Race Music"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Exception Recovery"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Faster Menu Navigation"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Boost Item Timer"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Long Distance Names"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "No Lakitu"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Remove Luma"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Faster Point Increase"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Mii Heads on Minimap"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Final Lap Music SpeedUp"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Colored Minimaps"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Better Mega FOV"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Race Count Modifier"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Show Finish Times"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "No DC in Idle"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Always Show Quit Confirmation"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "1st Person"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Accurate Item Roulette"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Random Combinations (Dolphin Only)"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Speedometer"
   Only one choice found: On - Use it? (Yes/No): Yes
  Option: "Items on Minimap"
   Only one choice found: On - Use it? (Yes/No): No
  Option: "Mute Character Voices"
   Only one choice found: On - Use it? (Yes/No): No

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Falling\Downloads\RiivolutionIsoBuilder\Insane_Kart_Wii_USA-eVEo6b\sys\main.dol'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at RiivolutionIsoBuilder.Dolpatcher..ctor(String dolPath, Boolean isSilent)
   at RiivolutionIsoBuilder.RiivolutionUniversalISOBuilder.doStuff(String ISOPath, String xmlPath, String outPath, String singleChoice, String newTitleID, String newGameName, Boolean isSilent, Boolean deleteISO, Int32 ignoreLevel, Boolean skipAllDone)
   at RiivolutionIsoBuilder.RiivolutionUniversalISOBuilder.Main(String[] args)
   at RiivolutionIsoBuilder.Program.Main(String[] args)

**Comment by Doge2-Official** [comment]
You're supposed to use XMLs not DOL's

**Comment by F-alling** [comment]
look near the end of the fifth line

**Comment by Asu-chan** [comment]
> !! wit: ERROR #14 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1932
> !!      Partition 0 [DATA]: End of data (0x1156c0000) behind end of file (0xffff8000):
> !!      /cygdrive/c/Users/Falling/Desktop/MarioKartWiiRMCE01.iso
> !! wit: ERROR #14 [INVALID WII PARTITION] in wd_check_part_offset() @ src/libwbfs/wiidisc.c#1921
> !!      Partition 2 [CHANNEL]: Offset of TICKET (0x1156c0000) behind end of file (0xffff8000):
> !!      /cygdrive/c/Users/Falling/Desktop/MarioKartWiiRMCE01.iso

> Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Falling\Downloads\RiivolutionIsoBuilder\Insane_Kart_Wii_USA-eVEo6b\sys\main.dol'.

This looks to me like the ISO you were using as a base is corrupted in some day, because wit is having trouble extracting it, resulting in there being no ``main.dol`` to patch.
Try to re-extract your ISO from your disc. Tell me if the problem persists.

**Comment by RuralAnemone** [comment]
are you by chance using this with wine? I'm getting the same error.

**Comment by F-alling** [comment]
nope, just windows
